### ISSUE TITLE
Disable tax calculator in settings

### ISSUE THREAD

**Issue by gabiudrescu** [FLUX-SE/SyliusEUVatPlugin#26]
If a shop is providing services only for one country, the plugin should allow the disable of the tax calculator, to avoid having orders with no taxes in the same country. Might run into legal / fiscal issues.

**Comment by Prometee** [comment]
Agree !

**Comment by Prometee** [comment]
Hello @gabiudrescu long time no see 😄

I would like to close this issue since the applicator will not process anything if no base country or no EU zone are selected in the channel setting.
